import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/Components/LayoutComponent/Header";
import Sidebar from "@/Components/LayoutComponent/Sidebar";
import SecondarySidebar from "@/Components/LayoutComponent/Sidebar/SecondarySidebar";

// const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body >
        <div className={`flex min-h-screen min-w-full font-sans relative overflow-x-hidden bg-white`}>
          <div className="w-full h-full flex">
            <div><Header /></div>
            <Sidebar />
            <SecondarySidebar />
            <div className="flex ml-[24rem] 
            mt-[78px] h-[calc(100vh_-_4.5rem)]
            overflow-y-scroll z-10 flex-grow font-sans p-2">{children}</div>
          </div></div></body></html>
  );
}
